version: '2.1'
services:
  registry-service:
    build: registry-service
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  gateway-service:
    build: gateway-service
    restart: always
    depends_on:
      registry-service:
        condition: service_started
    ports:
      - 80:4000
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  authoring-service:
    build: authoring-service
    restart: always
    depends_on:
      registry-service:
        condition: service_started
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  authoring-db:
    build: authoring-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=survey
    ports:
      - 27017:27017

 resultcapture-service:
    build: resultcapture-service
    restart: always
    depends_on:
      registry-service:
        condition: service_started
    logging:
      options:
        max-size: "10m"
        max-file: "10"
 capture-db:
    build: capture-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=result
    ports:
      - 27019:27017
