version: '3.3'
services:
  http-proxy:
    image: traefik
    container_name: traefik
    volumes:
      - ./http-proxy/traefik.toml:/etc/traefik/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
      - 8080:8080

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  ## DB instances ##
  authoring-db:
    build: authoring-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=survey
    ports:
      - 27017:27017

  capture-db:
    build: capture-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=results
    ports:
      - 27019:27017

  ## Application services ##
  authoring-service:
    build:
     context: authoring-service
     args:
       - java_opts=-Xmx256M
    depends_on:
      - authoring-db
      - kafka
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    labels:
      - "traefik.enable=true"
      - "traefik.port=7979"

  resultcapture-service:
    build:
     context: resultcapture-service
     args:
       - java_opts=-Xmx256M
    depends_on:
      - capture-db
      - kafka
    logging:
      options:
       max-size: "10m"
       max-file: "10"
    labels:
      - "traefik.enable=true"
      - "traefik.port=7979"

  analytics-service:
    build:
     context: analytics-service
     args:
      - java_opts=-Xmx256M
    depends_on:
      - kafka
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    labels:
      - "traefik.enable=true"
      - "traefik.port=7979"
