version: '3.3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 15672:15672
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  ## DB instances ##
  authoring-db:
    build: authoring-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=survey
    ports:
      - 27017:27017

  capture-db:
    build: capture-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=results
    ports:
      - 27019:27017

  ## Infrastructure services  ##
  registry-service:
    build:
     context: registry-service
     args:
       - java_opts=-Xmx256M
    restart: always
    ports:
      - 8761:8761
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  gateway-service:
    build:
     context: gateway-service
     args:
       - java_opts=-Xmx256M
    restart: always
    depends_on:
      - registry-service
    ports:
      - 80:4000
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  monitoring-hystrix:
    build:
     context: monitoring-hystrix
     args:
       - java_opts=-Xmx256M
    restart: always
    ports:
      - 9090:8080
      - 8989:8989
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  monitoring-zipkin:
    build:
     context: monitoring-zipkin
     args:
       - java_opts=-Xmx256M
    restart: always
    ports:
      - 8888:8080
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  ## Application services ##
  authoring-service:
    build:
     context: authoring-service
     args:
       - java_opts=-Xmx256M
    restart: always
    depends_on:
      - registry-service
      - authoring-db
    logging:
      options:
        max-size: "10m"
        max-file: "10"
  resultcapture-service:
    build:
     context: resultcapture-service
     args:
       - java_opts=-Xmx256M
    restart: always
    depends_on:
      - registry-service
      - capture-db
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  analytics-service:
    build:
     context: analytics-service
     args:
      - java_opts=-Xmx256M
    restart: always
    depends_on:
      - registry-service
      - authoring-service
      - resultcapture-service
    logging:
      options:
        max-size: "10m"
        max-file: "10"
