spring:
  application:
    name: resultcapture-service
  data:
    mongodb:
      host: capture-db
      username: user
      password: password
      database: results
      port: 27017

kafka:
  bootstrapAddress: kafka:9092
  consumerGroupName: resultCaptureGroup
  resultCapturedTopic: result-captured
  resultStoredTopic: result-stored

server:
  port: 7979

logging:
  level:
    com.devotion.capture: DEBUG

api:
  version: 1.0
  title: Survey submission API
  description: Operations on this API allows you to capture results of survey submission
  contactEmail: devotion-dev@gmail.com