spring:
  application:
    name: resultcapture-service
  data:
    mongodb:
      host: capture-db
      username: user
      password: password
      database: results
      port: 27017
1kafka:
  servers: kafka:9092


server:
  context-path: /capture/
  port: 7979

logging:
  level:
    com.draganlj.survey: DEBUG


api:
  version: 1.0