spring:
  application:
    name: resultcapture-service
  data:
    mongodb:
      host: capture-db
      username: user
      password: password
      database: results
      port: 27017
kafka:
  bootstrap-servers: kafka:9092
  consumer-group: resultCaptureGroup
  result-captured-topic: result-captured
  result-stored-topic: result-stored



server:
  servlet:
    context-path: /capture/
  port: 7979

logging:
  level:
    com.draganlj.survey: DEBUG


api:
  version: 1.0