spring:
  application:
    name: resultcapture-service
  data:
    mongodb:
      host: capture-db
      username: user
      password: password
      database: results
      port: 27017
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://registry-service:8761/eureka/

server:
  context-path: /capture/
  port: 7979

logging:
  level:
    com.draganlj.survey: DEBUG

api:
  version: 1.o