spring:
  application:
    name: analytics-service
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://registry-service:8761/eureka/
feign:
  hystrix:
    enabled: false

server:
  context-path: /analytics/
  port: 7676

logging:
  level:
    com.draganlj.survey: DEBUG

api:
  version: 1.0