spring:
  application:
    name: authoring-service
  data:
    mongodb:
      host: authoring-db
      username: user
      password: password
      database: survey
      port: 27017
server:
  servlet:
    context-path: /authoring/
  port: 7878
logging:
  level:
    com.draganlj.survey: DEBUG

api:
  version: 1.0