spring:
  application:
    name: authoring-service
  data:
    mongodb:
      host: authoring-db
      username: user
      password: password
      database: survey
      port: 27017
  rabbitmq:
    host: rabbitmq
  sleuth:
    sampler:
      percentage: 1

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://registry-service:8761/eureka/

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

server:
  context-path: /authoring/
  port: 7878
logging:
  level:
    com.draganlj.survey: DEBUG

api:
  version: 1.0