spring:
  application:
    name: authoring-service
  data:
    mongodb:
      host: authoring-db
      username: user
      password: password
      database: survey
      port: 27017
server:
  port: 7979
logging:
  level:
    com.draganlj.survey: DEBUG

api:
  version: 1.0